[package]
name = "pluvio_ucx"
version = "0.1.0"
edition = "2021"

[dependencies]
async-ucx = { path = "lib/async-ucx", features = ["am"] }
pluvio_runtime = { path = "../pluvio_runtime" }
slab = "0.4.10"
tracing = {workspace = true}